### Crops a directory of cards generated by MPCfill for normal use

import os
import math

import click
from PIL import Image

DEFAULT_CROP_DIRECTORY = os.path.join('game', 'crop')
DEFAULT_CROP = 6.5
DEFAULT_IMAGE_TYPE = "jpg"

@click.command()
@click.option("--card_dir", default=DEFAULT_CROP_DIRECTORY, show_default=True, help="The path to the directory containing the card fronts.")
@click.option("--crop", default=6.5, type=click.FloatRange(min=0, max=100), help="Crop a percentage of the outer portion of front and double-sided images, useful for existing print bleed.")
@click.option("--image_format", default=DEFAULT_IMAGE_TYPE, show_default=True, help="Expected image format. Typically jpg from MPCfill.")

def main(card_dir, crop, image_format):
    if not os.path.exists(card_dir):
        raise Exception(f'Invalid Path. {card_dir} does not exist.')
    
    if os.path.isfile(card_dir):
        raise Exception(f'Supplied path {card_dir} is a file. Must be a directory.')

    cards = get_cards(card_dir, image_format)

    print(f'Cropping {len(cards)} cards...')
    for fp, card in cards.items():
        print(fp)
        card = crop_card(card, crop)
        card.save(fp)
    
    print(f'done.')

def get_cards(card_dir: str, image_type: str) -> {str: Image.Image}:
    cards = {}
    image_type = '.'*(not image_type.startswith('.')) + image_type

    for item in os.listdir(card_dir):
        full_path = os.path.join(card_dir, item)
        if not os.path.isfile(full_path):
            continue

        if not os.path.splitext(full_path)[-1] == image_type:
            continue

        cards[full_path] = Image.open(full_path)

    return cards

def crop_card(card_image: Image.Image, crop: float) -> Image.Image:
    card_width, card_height = card_image.size
    card_width_crop = math.floor(card_width / 2 * (crop / 100))
    card_height_crop = math.floor(card_height / 2 * (crop / 100))
    return card_image.crop((card_width_crop, card_height_crop, card_width - card_width_crop, card_height - card_height_crop))


if __name__ == '__main__':
     main()